// Copyright 2026 pakkio and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAssetsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "assets",
		Short:       "Online asset search (Poly Haven/Sketchfab/ambientCG) and AI text-to-3D generation (Meshy/Tripo/Trellis).",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAssetsAiGenerateCmd(flags))
	cmd.AddCommand(newAssetsAssetBrowserCmd(flags))
	cmd.AddCommand(newAssetsImportOnlineCmd(flags))
	cmd.AddCommand(newAssetsSearchOnlineCmd(flags))
	return cmd
}
