// Copyright 2026 pakkio and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAssetsSearchOnlineCmd(flags *rootFlags) *cobra.Command {
	var bodyQuery string
	var bodyAssetType string
	var bodyProviders string
	var bodyLimit string
	var bodyFreeOnly string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "search-online",
		Short:       "",
		Example:     "  mcp-blender-pp-cli assets search-online",
		Annotations: map[string]string{"pp:endpoint": "assets.search_online", "pp:method": "POST", "pp:path": "/blender_assets/search_online", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("query") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "query")
				}
			}
			path := "/blender_assets/search_online"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if cmd.Flags().Changed("query") || bodyQuery != "" {
					bodyMap["query"] = bodyQuery
				}
				if cmd.Flags().Changed("asset-type") || bodyAssetType != "" {
					bodyMap["asset_type"] = bodyAssetType
				}
				if cmd.Flags().Changed("providers") || bodyProviders != "" {
					bodyMap["providers"] = bodyProviders
				}
				if cmd.Flags().Changed("limit") || bodyLimit != "" {
					bodyMap["limit"] = bodyLimit
				}
				if cmd.Flags().Changed("free-only") || bodyFreeOnly != "" {
					bodyMap["free_only"] = bodyFreeOnly
				}
			}
			data, statusCode, err := c.PostQueryWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			if isDryRunResponse(c.IsDryRun(), data) {
				if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
					return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "dry-run"}, nil)
				}
				return nil
			}
			_ = statusCode
			outputData := data
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, nil)
		},
	}
	cmd.Flags().StringVar(&bodyQuery, "query", "", "search text")
	cmd.Flags().StringVar(&bodyAssetType, "asset-type", "", "MODEL, HDRI, TEXTURE")
	cmd.Flags().StringVar(&bodyProviders, "providers", "", "provider filter list")
	cmd.Flags().StringVar(&bodyLimit, "limit", "", "max results")
	cmd.Flags().StringVar(&bodyFreeOnly, "free-only", "", "CC0/free only flag")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
