// Copyright 2026 pakkio and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCameraLightingCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "camera-lighting",
		Short:       "Studio/sun-sky lighting rigs, camera tracking/framing, viewport screenshots, AI visual critique.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCameraLightingCameraSetupCmd(flags))
	cmd.AddCommand(newCameraLightingCompositorEffectsCmd(flags))
	cmd.AddCommand(newCameraLightingEvaluateSceneCmd(flags))
	cmd.AddCommand(newCameraLightingFrameObjectsCmd(flags))
	cmd.AddCommand(newCameraLightingLightSetupCmd(flags))
	cmd.AddCommand(newCameraLightingLookAtCmd(flags))
	cmd.AddCommand(newCameraLightingScreenshotCmd(flags))
	cmd.AddCommand(newCameraLightingStudioLightingCmd(flags))
	cmd.AddCommand(newCameraLightingSunSkyRigCmd(flags))
	return cmd
}
