// Copyright 2026 pakkio and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMaterialCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "material",
		Short:       "PBR shading, procedural grunge masks, toon shaders, alpha transparency, triplanar mapping, and material slots.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newMaterialAssignCmd(flags))
	cmd.AddCommand(newMaterialCreateCmd(flags))
	cmd.AddCommand(newMaterialEditNodesCmd(flags))
	cmd.AddCommand(newMaterialPbrSetupCmd(flags))
	cmd.AddCommand(newMaterialProceduralGrungeCmd(flags))
	cmd.AddCommand(newMaterialSlotsCmd(flags))
	cmd.AddCommand(newMaterialToonShaderCmd(flags))
	cmd.AddCommand(newMaterialTransparencyCmd(flags))
	cmd.AddCommand(newMaterialTriplanarCmd(flags))
	return cmd
}
