// Copyright 2026 pakkio and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMeshCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "mesh",
		Short:       "3D modeling, transforms, boolean CSG, decimation, voxel remesh, UV unwrap, and modifiers.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newMeshApplyTransformCmd(flags))
	cmd.AddCommand(newMeshBooleanCmd(flags))
	cmd.AddCommand(newMeshCreateCmd(flags))
	cmd.AddCommand(newMeshDecimateCmd(flags))
	cmd.AddCommand(newMeshDeleteCmd(flags))
	cmd.AddCommand(newMeshDuplicateCmd(flags))
	cmd.AddCommand(newMeshMeshOpCmd(flags))
	cmd.AddCommand(newMeshModifierCmd(flags))
	cmd.AddCommand(newMeshOriginCursorCmd(flags))
	cmd.AddCommand(newMeshRemeshCmd(flags))
	cmd.AddCommand(newMeshSimplifyGeometryCmd(flags))
	cmd.AddCommand(newMeshTransformCmd(flags))
	cmd.AddCommand(newMeshUvUnwrapCmd(flags))
	return cmd
}
