// Copyright 2026 pakkio and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPhysicsSimCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "physics-sim",
		Short:       "Rigid body physics, cloth simulation, wind/vortex forces, fluid domain baking, scene physics settings.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPhysicsSimAddForceFieldCmd(flags))
	cmd.AddCommand(newPhysicsSimBakeFluidCmd(flags))
	cmd.AddCommand(newPhysicsSimConfigurePhysicsCmd(flags))
	cmd.AddCommand(newPhysicsSimSetupClothCmd(flags))
	cmd.AddCommand(newPhysicsSimSetupRigidBodyCmd(flags))
	return cmd
}
