// Copyright 2026 pakkio and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newEvaluateSceneVisuallyPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyCameraName string
	var bodyPrompt string
	var bodyResolution string

	cmd := &cobra.Command{
		Use:         "evaluate-scene-visually",
		Short:       "",
		Long:        "",
		Example:     "  mcp-blender-pp-cli evaluate-scene-visually",
		Annotations: map[string]string{"pp:endpoint": "evaluate_scene_visually.evaluate", "pp:method": "POST", "pp:path": "/evaluate_scene_visually"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/evaluate_scene_visually"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			bodyMap := map[string]any{}
			var body any = bodyMap
			if cmd.Flags().Changed("camera-name") || bodyCameraName != "" {
				bodyMap["camera_name"] = bodyCameraName
			}
			if cmd.Flags().Changed("prompt") || bodyPrompt != "" {
				bodyMap["prompt"] = bodyPrompt
			}
			if cmd.Flags().Changed("resolution") || bodyResolution != "" {
				bodyMap["resolution"] = bodyResolution
			}
			data, _, err := c.PostWithParams(cmd.Context(), path, params, body)

			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := data
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, nil)
		},
	}
	cmd.Flags().StringVar(&bodyCameraName, "camera-name", "", "")
	cmd.Flags().StringVar(&bodyPrompt, "prompt", "", "")
	cmd.Flags().StringVar(&bodyResolution, "resolution", "", "")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
