// Copyright 2026 pakkio and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newImportOnlineAssetPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyAssetId string
	var bodyProvider string
	var bodyTargetPolyBudget string
	var bodyCollectionPath string
	var bodyLocation string
	var bodyScaleToSize string
	var bodyForwardAxis string
	var bodyUpAxis string
	var bodyAutoOrient string

	cmd := &cobra.Command{
		Use:         "import-online-asset",
		Short:       "",
		Long:        "",
		Example:     "  mcp-blender-pp-cli import-online-asset",
		Annotations: map[string]string{"pp:endpoint": "import_online_asset.import", "pp:method": "POST", "pp:path": "/import_online_asset"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with a required flag/body prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only reads fall through so a bare call still executes; positional
			// commands keep their existing usageErr (exit 2 + JSON envelope).
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !cmd.Flags().Changed("asset-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "asset-id")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/import_online_asset"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			bodyMap := map[string]any{}
			var body any = bodyMap
			if cmd.Flags().Changed("asset-id") || bodyAssetId != "" {
				bodyMap["asset_id"] = bodyAssetId
			}
			if cmd.Flags().Changed("provider") || bodyProvider != "" {
				bodyMap["provider"] = bodyProvider
			}
			if cmd.Flags().Changed("target-poly-budget") || bodyTargetPolyBudget != "" {
				bodyMap["target_poly_budget"] = bodyTargetPolyBudget
			}
			if cmd.Flags().Changed("collection-path") || bodyCollectionPath != "" {
				bodyMap["collection_path"] = bodyCollectionPath
			}
			if cmd.Flags().Changed("location") || bodyLocation != "" {
				bodyMap["location"] = bodyLocation
			}
			if cmd.Flags().Changed("scale-to-size") || bodyScaleToSize != "" {
				bodyMap["scale_to_size"] = bodyScaleToSize
			}
			if cmd.Flags().Changed("forward-axis") || bodyForwardAxis != "" {
				bodyMap["forward_axis"] = bodyForwardAxis
			}
			if cmd.Flags().Changed("up-axis") || bodyUpAxis != "" {
				bodyMap["up_axis"] = bodyUpAxis
			}
			if cmd.Flags().Changed("auto-orient") || bodyAutoOrient != "" {
				bodyMap["auto_orient"] = bodyAutoOrient
			}
			data, _, err := c.PostWithParams(cmd.Context(), path, params, body)

			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := data
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, nil)
		},
	}
	cmd.Flags().StringVar(&bodyAssetId, "asset-id", "", "")
	cmd.Flags().StringVar(&bodyProvider, "provider", "", "")
	cmd.Flags().StringVar(&bodyTargetPolyBudget, "target-poly-budget", "", "")
	cmd.Flags().StringVar(&bodyCollectionPath, "collection-path", "", "")
	cmd.Flags().StringVar(&bodyLocation, "location", "", "")
	cmd.Flags().StringVar(&bodyScaleToSize, "scale-to-size", "", "")
	cmd.Flags().StringVar(&bodyForwardAxis, "forward-axis", "", "")
	cmd.Flags().StringVar(&bodyUpAxis, "up-axis", "", "")
	cmd.Flags().StringVar(&bodyAutoOrient, "auto-orient", "", "")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
