// Copyright 2026 pakkio and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newSimplifyGeometryPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyObjectName string
	var bodyTargetVerts string
	var bodyMaxDeviationPct string
	var bodyAllowNewHoles string
	var bodyRollbackOnFailure string

	cmd := &cobra.Command{
		Use:         "simplify-geometry",
		Short:       "",
		Long:        "",
		Example:     "  mcp-blender-pp-cli simplify-geometry",
		Annotations: map[string]string{"pp:endpoint": "simplify_geometry.simplify", "pp:method": "POST", "pp:path": "/simplify_geometry"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with a required flag/body prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only reads fall through so a bare call still executes; positional
			// commands keep their existing usageErr (exit 2 + JSON envelope).
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !cmd.Flags().Changed("object-name") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "object-name")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/simplify_geometry"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			bodyMap := map[string]any{}
			var body any = bodyMap
			if cmd.Flags().Changed("object-name") || bodyObjectName != "" {
				bodyMap["object_name"] = bodyObjectName
			}
			if cmd.Flags().Changed("target-verts") || bodyTargetVerts != "" {
				bodyMap["target_verts"] = bodyTargetVerts
			}
			if cmd.Flags().Changed("max-deviation-pct") || bodyMaxDeviationPct != "" {
				bodyMap["max_deviation_pct"] = bodyMaxDeviationPct
			}
			if cmd.Flags().Changed("allow-new-holes") || bodyAllowNewHoles != "" {
				bodyMap["allow_new_holes"] = bodyAllowNewHoles
			}
			if cmd.Flags().Changed("rollback-on-failure") || bodyRollbackOnFailure != "" {
				bodyMap["rollback_on_failure"] = bodyRollbackOnFailure
			}
			data, _, err := c.PostWithParams(cmd.Context(), path, params, body)

			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := data
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, nil)
		},
	}
	cmd.Flags().StringVar(&bodyObjectName, "object-name", "", "")
	cmd.Flags().StringVar(&bodyTargetVerts, "target-verts", "", "")
	cmd.Flags().StringVar(&bodyMaxDeviationPct, "max-deviation-pct", "", "default 2.0")
	cmd.Flags().StringVar(&bodyAllowNewHoles, "allow-new-holes", "", "default 0")
	cmd.Flags().StringVar(&bodyRollbackOnFailure, "rollback-on-failure", "", "default true")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
