// Copyright 2026 pakkio and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRenderPipelineCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "render-pipeline",
		Short:       "Still/animation rendering, PBR texture baking, Unity FBX export, LOD chain generation, VFX tracking.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newRenderPipelineBakeTexturesCmd(flags))
	cmd.AddCommand(newRenderPipelineExportUnityFbxCmd(flags))
	cmd.AddCommand(newRenderPipelineGenerateLodsCmd(flags))
	cmd.AddCommand(newRenderPipelineRenderAnimCmd(flags))
	cmd.AddCommand(newRenderPipelineRenderImageCmd(flags))
	cmd.AddCommand(newRenderPipelineVfxShadowCatcherCmd(flags))
	cmd.AddCommand(newRenderPipelineVfxTrackingCmd(flags))
	return cmd
}
