// Copyright 2026 pakkio and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRiggingAnimCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "rigging-anim",
		Short:       "Armatures, bone posing, IK rigs, hair curves creation/grooming, animation keyframes, turntable animation.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newRiggingAnimApplyHairGroomCmd(flags))
	cmd.AddCommand(newRiggingAnimCreateArmatureCmd(flags))
	cmd.AddCommand(newRiggingAnimCreateHairCurvesCmd(flags))
	cmd.AddCommand(newRiggingAnimPoseBoneCmd(flags))
	cmd.AddCommand(newRiggingAnimSetKeyframeCmd(flags))
	cmd.AddCommand(newRiggingAnimSetupHumanoidRigCmd(flags))
	cmd.AddCommand(newRiggingAnimSetupIkCmd(flags))
	cmd.AddCommand(newRiggingAnimTimelineRangeCmd(flags))
	cmd.AddCommand(newRiggingAnimTurntableCmd(flags))
	return cmd
}
