// Copyright 2026 pakkio and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSceneCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "scene",
		Short:       "Scene inspection, hierarchy organization, checkpoint rollback, orphan purging, and background jobs.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSceneBusyCmd(flags))
	cmd.AddCommand(newSceneCheckpointCreateCmd(flags))
	cmd.AddCommand(newSceneCheckpointListCmd(flags))
	cmd.AddCommand(newSceneCheckpointRestoreCmd(flags))
	cmd.AddCommand(newSceneCollectionCmd(flags))
	cmd.AddCommand(newSceneHierarchyCmd(flags))
	cmd.AddCommand(newSceneInfoCmd(flags))
	cmd.AddCommand(newSceneJobCancelCmd(flags))
	cmd.AddCommand(newSceneJobListCmd(flags))
	cmd.AddCommand(newSceneJobStatusCmd(flags))
	cmd.AddCommand(newScenePerformanceCmd(flags))
	cmd.AddCommand(newScenePurgeOrphansCmd(flags))
	cmd.AddCommand(newSceneRegenCmd(flags))
	return cmd
}
