"""Trellis AI: Microsoft Research 3D Generative Model (via Hugging Face
Inference Endpoint).
Requires:
- TRELLIS_ENDPOINT_URL: an active HF Inference Endpoint running a Trellis
  image-to-3D handler (no official hosted API exists for it), and
- TRELLIS_API_KEY or HF_TOKEN: the bearer token for that endpoint.
https://github.com/microsoft/TRELLIS
"""

import base64
import json
import os
from pathlib import Path
import httpx

from ..cache import find_cached_file
from . import _image as image_util
from .base import AssetHit, DownloadedAsset, ProviderError


class TrellisProvider:
    name = "trellis"
    requires_token = True

    def _get_token(self) -> str | None:
        return os.environ.get("TRELLIS_API_KEY") or os.environ.get("HF_TOKEN")

    def _get_endpoint(self) -> str | None:
        return os.environ.get("TRELLIS_ENDPOINT_URL")

    def is_available(self) -> bool:
        return bool(self._get_token())

    async def search(self, query: str, asset_type: str, limit: int) -> list[AssetHit]:
        if asset_type != "MODEL":
            return []

        return [
            AssetHit(
                id=f"trellis_{query.replace(' ', '_')[:30]}",
                provider=self.name,
                name=f"Trellis AI Generation: '{query}'",
                asset_type="MODEL",
                license="Open / Research",
                requires_token=True,
                tri_count_hint=35000,
                extra={"prompt": query, "note": "Requires TRELLIS_ENDPOINT_URL + TRELLIS_API_KEY or HF_TOKEN"},
            )
        ]

    async def download(
        self, asset_id: str, dest_dir: str, image_path: str | None = None
    ) -> DownloadedAsset:
        cached = find_cached_file(self.name, asset_id)
        if cached is not None:
            return DownloadedAsset(
                filepath=str(cached),
                provider=self.name,
                asset_id=asset_id,
                license="Open / Research",
                attribution=f"'{asset_id}' generated by Trellis 3D",
                from_cache=True,
            )

        if not image_path:
            # Text-only generation was never implemented: Trellis has no
            # hosted text-to-3D API, only self-hosted endpoints fed an image.
            raise ProviderError(
                "Trellis only supports image-to-3d here. Pass image_path pointing "
                "to an existing .png/.jpg/.jpeg/.webp file, plus TRELLIS_ENDPOINT_URL "
                "and TRELLIS_API_KEY (or HF_TOKEN)."
            )

        endpoint = self._get_endpoint()
        token = self._get_token()
        if not endpoint:
            raise ProviderError(
                "Trellis image-to-3d requires TRELLIS_ENDPOINT_URL pointing at an "
                "active HF Inference Endpoint running a Trellis handler."
            )
        if not token:
            raise ProviderError("Trellis requires TRELLIS_API_KEY or HF_TOKEN environment variable.")

        headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
        payload = {"inputs": image_util.to_data_uri(image_path)}

        async with httpx.AsyncClient(timeout=600.0) as client:
            resp = await client.post(endpoint, headers=headers, json=payload)
            if resp.status_code != 200:
                raise ProviderError(f"Trellis endpoint request failed: HTTP {resp.status_code} - {resp.text[:300]}")

            glb_bytes = self._extract_glb(resp)

        out_file = Path(dest_dir) / f"{asset_id}.glb"
        out_file.parent.mkdir(parents=True, exist_ok=True)
        out_file.write_bytes(glb_bytes)

        return DownloadedAsset(
            filepath=str(out_file),
            provider=self.name,
            asset_id=asset_id,
            license="Open / Research",
            attribution=f"'{asset_id}' generated by Trellis 3D (image-to-3d)",
            from_cache=False,
        )

    @staticmethod
    def _extract_glb(resp: httpx.Response) -> bytes:
        """Endpoints vary in what they return: raw GLB bytes, JSON with a
        base64 payload, or JSON with a download URL. Accept all three rather
        than hard-coupling to one custom handler's convention."""
        body = resp.content
        if body[:4] == b"glTF":
            return body

        try:
            data = json.loads(body)
        except (json.JSONDecodeError, UnicodeDecodeError):
            data = None

        if isinstance(data, dict):
            if isinstance(data.get("url"), str):
                dl = httpx.get(data["url"], timeout=120.0)
                if dl.status_code == 200 and dl.content[:4] == b"glTF":
                    return dl.content
                raise ProviderError(
                    f"Trellis endpoint returned a model URL but the download failed: HTTP {dl.status_code}"
                )
            for key in ("glb_base64", "model_base64", "base64", "glb"):
                value = data.get(key)
                if isinstance(value, str):
                    try:
                        decoded = base64.b64decode(value)
                    except Exception:
                        continue
                    if decoded[:4] == b"glTF":
                        return decoded
            raise ProviderError(
                f"Trellis endpoint returned unrecognised JSON keys: {sorted(data.keys())}. "
                "Expected one of: url / glb_base64 / model_base64 / base64 / glb, or raw GLB bytes."
            )

        raise ProviderError(
            "Trellis endpoint returned neither raw GLB bytes nor recognised JSON. "
            "Check that the endpoint runs a Trellis image-to-3D handler."
        )
