"""Trellis AI: Microsoft Research 3D Generative Model (via Hugging Face / replicate API).
Requires TRELLIS_API_KEY or HF_TOKEN environment variable.
https://github.com/microsoft/TRELLIS
"""

import os
from pathlib import Path
import httpx

from ..cache import find_cached_file
from .base import AssetHit, DownloadedAsset, ProviderError


class TrellisProvider:
    name = "trellis"
    requires_token = True

    def _get_token(self) -> str | None:
        return os.environ.get("TRELLIS_API_KEY") or os.environ.get("HF_TOKEN")

    def is_available(self) -> bool:
        return bool(self._get_token())

    async def search(self, query: str, asset_type: str, limit: int) -> list[AssetHit]:
        if asset_type != "MODEL":
            return []

        return [
            AssetHit(
                id=f"trellis_{query.replace(' ', '_')[:30]}",
                provider=self.name,
                name=f"Trellis AI Generation: '{query}'",
                asset_type="MODEL",
                license="Open / Research",
                requires_token=True,
                tri_count_hint=35000,
                extra={"prompt": query, "note": "Requires TRELLIS_API_KEY or HF_TOKEN"},
            )
        ]

    async def download(self, asset_id: str, dest_dir: str) -> DownloadedAsset:
        cached = find_cached_file(self.name, asset_id)
        if cached is not None:
            return DownloadedAsset(
                filepath=str(cached),
                provider=self.name,
                asset_id=asset_id,
                license="Open / Research",
                attribution=f"'{asset_id}' generated by Trellis 3D",
                from_cache=True,
            )

        token = self._get_token()
        if not token:
            raise ProviderError("Trellis 3D requires TRELLIS_API_KEY or HF_TOKEN environment variable.")

        # In case a local/cached test asset exists or custom endpoint
        raise ProviderError(f"Trellis endpoint generation in progress for '{asset_id}'. Please configure active HF Inference Endpoint.")
