// Copyright 2026 pakkio and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package mcp — code-orchestration thin surface.
//
// Three tools cover the entire API: <api>_search to discover endpoints,
// <api>_get to inspect one GET endpoint, and <api>_execute to invoke one.
// This collapses a large API (50+ endpoints)
// to ~1K tokens of tool definitions while preserving full coverage — the
// agent writes the composition logic in its own sandbox.
//
// Pattern source: Anthropic 2026-04-22 "Building agents that reach
// production systems with MCP" — Cloudflare's MCP server covers ~2,500
// endpoints in roughly 1K tokens via the same search, get, and execute shape.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	neturl "net/url"
	"sort"
	"strings"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"mcp-blender-pp-cli/internal/cli"
	"mcp-blender-pp-cli/internal/mcp/bound"
)

// RegisterCodeOrchestrationTools registers the agent-facing tools that cover
// the whole API surface. Called from RegisterTools in place of the per-endpoint
// registrations when MCP.Orchestration is "code".
func RegisterCodeOrchestrationTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("mcp-blender_search",
			mcplib.WithDescription("Search the mcp-blender API for endpoints matching a natural-language query. Returns a ranked list of {endpoint_id, method, path, summary} entries. Call this first to find the endpoint to execute."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Natural-language description of what you want to do.")),
			mcplib.WithNumber("limit", mcplib.Description("Max endpoints to return (default 10, max 100).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(false),
		),
		handleCodeOrchSearch,
	)

	s.AddTool(
		mcplib.NewTool("mcp-blender_get",
			mcplib.WithDescription("Get metadata for one GET endpoint by its endpoint_id (from mcp-blender_search). This registry-only lookup never calls the API."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("GET endpoint identifier returned by mcp-blender_search (e.g., \"users.list\").")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(false),
		),
		handleCodeOrchGet,
	)

	s.AddTool(
		mcplib.NewTool("mcp-blender_execute",
			mcplib.WithDescription("Execute one mcp-blender API endpoint by its endpoint_id (from mcp-blender_search). Params are passed as a JSON object; path placeholders and query strings are resolved automatically."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("Endpoint identifier returned by mcp-blender_search (e.g., \"users.list\").")),
			mcplib.WithObject("params", mcplib.Description("Parameters for the endpoint. Path placeholders match by name; remaining entries become query string on GET/DELETE or JSON body on POST/PUT/PATCH.")),
		),
		handleCodeOrchExecute,
	)
}

// codeOrchEndpoint captures the small slice of endpoint metadata the
// registry tools need at runtime. `keywords` is a precomputed
// lowercase stream of description + path tokens used for naive ranking;
// anything more sophisticated belongs on the agent side.
type codeOrchEndpoint struct {
	ID         string
	Method     string
	Path       string
	Tier       string
	Summary    string
	Positional []string
	// TemplateParams carries public-to-wire bindings for promoted global path
	// placeholders. These resolve through Config.TemplateVars just like the
	// per-endpoint MCP tool inputs do.
	TemplateParams []codeOrchParamBinding
	// QueryParams carries public-to-wire bindings for spec-declared in:query
	// parameters. Write methods (POST/PUT/PATCH) route these to the query
	// string instead of dumping them into the JSON body. Derived from the
	// same mcpParamBindings location data the per-endpoint tools use.
	QueryParams []codeOrchParamBinding
	// Keep declared headers out of query/body routing so execution sends them
	// through the request-header map.
	HeaderParams []codeOrchParamBinding
	// HeaderOverrides carries per-endpoint request headers (e.g. an
	// Accept override for binary-only response endpoints). Without
	// threading these through, the code-orchestration execute path
	// sends the client's default Accept and binary endpoints 406.
	HeaderOverrides map[string]string
	// BodyIsArray marks endpoints whose request body schema root is a
	// bare top-level JSON array. The execute path then sends a top-level
	// array (the agent supplies it as params["body"]) instead of the
	// params object; a strict-mapping API rejects an object at the body
	// root with HTTP 422 "Invalid json".
	BodyIsArray bool
	Mutating    bool
	keywords    []string
}

type codeOrchParamBinding struct {
	PublicName string
	WireName   string
	Default    string
}

// codeOrchEndpoints is the generator-populated registry covering every
// endpoint declared in the spec. Kept flat on purpose — the agent queries
// via <api>_search, so hierarchy shows up as dotted IDs, not nested maps.
var codeOrchEndpoints = []codeOrchEndpoint{
	{
		ID:             "assets.ai_generate",
		Method:         "POST",
		Path:           "/blender_assets/ai_generate",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("assets", "ai_generate", "", "/blender_assets/ai_generate"),
	},
	{
		ID:             "assets.asset_browser",
		Method:         "POST",
		Path:           "/blender_assets/asset_browser",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("assets", "asset_browser", "", "/blender_assets/asset_browser"),
	},
	{
		ID:             "assets.import_online",
		Method:         "POST",
		Path:           "/blender_assets/import_online",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("assets", "import_online", "", "/blender_assets/import_online"),
	},
	{
		ID:             "assets.search_online",
		Method:         "POST",
		Path:           "/blender_assets/search_online",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("assets", "search_online", "", "/blender_assets/search_online"),
	},
	{
		ID:             "camera_lighting.camera_setup",
		Method:         "POST",
		Path:           "/blender_camera_lighting/camera_setup",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("camera_lighting", "camera_setup", "", "/blender_camera_lighting/camera_setup"),
	},
	{
		ID:             "camera_lighting.compositor_effects",
		Method:         "POST",
		Path:           "/blender_camera_lighting/compositor_effects",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("camera_lighting", "compositor_effects", "", "/blender_camera_lighting/compositor_effects"),
	},
	{
		ID:             "camera_lighting.evaluate_scene",
		Method:         "POST",
		Path:           "/blender_camera_lighting/evaluate_scene",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("camera_lighting", "evaluate_scene", "", "/blender_camera_lighting/evaluate_scene"),
	},
	{
		ID:             "camera_lighting.frame_objects",
		Method:         "POST",
		Path:           "/blender_camera_lighting/frame_objects",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("camera_lighting", "frame_objects", "", "/blender_camera_lighting/frame_objects"),
	},
	{
		ID:             "camera_lighting.light_setup",
		Method:         "POST",
		Path:           "/blender_camera_lighting/light_setup",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("camera_lighting", "light_setup", "", "/blender_camera_lighting/light_setup"),
	},
	{
		ID:             "camera_lighting.look_at",
		Method:         "POST",
		Path:           "/blender_camera_lighting/look_at",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("camera_lighting", "look_at", "", "/blender_camera_lighting/look_at"),
	},
	{
		ID:             "camera_lighting.screenshot",
		Method:         "POST",
		Path:           "/blender_camera_lighting/screenshot",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("camera_lighting", "screenshot", "", "/blender_camera_lighting/screenshot"),
	},
	{
		ID:             "camera_lighting.studio_lighting",
		Method:         "POST",
		Path:           "/blender_camera_lighting/studio_lighting",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("camera_lighting", "studio_lighting", "", "/blender_camera_lighting/studio_lighting"),
	},
	{
		ID:             "camera_lighting.sun_sky_rig",
		Method:         "POST",
		Path:           "/blender_camera_lighting/sun_sky_rig",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("camera_lighting", "sun_sky_rig", "", "/blender_camera_lighting/sun_sky_rig"),
	},
	{
		ID:             "docs.search",
		Method:         "POST",
		Path:           "/blender_docs",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("docs", "search", "", "/blender_docs"),
	},
	{
		ID:             "evaluate_scene_visually.evaluate",
		Method:         "POST",
		Path:           "/evaluate_scene_visually",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("evaluate_scene_visually", "evaluate", "", "/evaluate_scene_visually"),
	},
	{
		ID:             "import_online_asset.import",
		Method:         "POST",
		Path:           "/import_online_asset",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("import_online_asset", "import", "", "/import_online_asset"),
	},
	{
		ID:             "material.assign",
		Method:         "POST",
		Path:           "/blender_material/assign",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("material", "assign", "", "/blender_material/assign"),
	},
	{
		ID:             "material.create",
		Method:         "POST",
		Path:           "/blender_material/create",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("material", "create", "", "/blender_material/create"),
	},
	{
		ID:             "material.edit_nodes",
		Method:         "POST",
		Path:           "/blender_material/edit_nodes",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("material", "edit_nodes", "", "/blender_material/edit_nodes"),
	},
	{
		ID:             "material.pbr_setup",
		Method:         "POST",
		Path:           "/blender_material/pbr_setup",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("material", "pbr_setup", "", "/blender_material/pbr_setup"),
	},
	{
		ID:             "material.procedural_grunge",
		Method:         "POST",
		Path:           "/blender_material/procedural_grunge",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("material", "procedural_grunge", "", "/blender_material/procedural_grunge"),
	},
	{
		ID:             "material.slots",
		Method:         "POST",
		Path:           "/blender_material/slots",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("material", "slots", "", "/blender_material/slots"),
	},
	{
		ID:             "material.toon_shader",
		Method:         "POST",
		Path:           "/blender_material/toon_shader",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("material", "toon_shader", "", "/blender_material/toon_shader"),
	},
	{
		ID:             "material.transparency",
		Method:         "POST",
		Path:           "/blender_material/transparency",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("material", "transparency", "", "/blender_material/transparency"),
	},
	{
		ID:             "material.triplanar",
		Method:         "POST",
		Path:           "/blender_material/triplanar",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("material", "triplanar", "", "/blender_material/triplanar"),
	},
	{
		ID:             "mesh.apply_transform",
		Method:         "POST",
		Path:           "/blender_mesh/apply_transform",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("mesh", "apply_transform", "", "/blender_mesh/apply_transform"),
	},
	{
		ID:             "mesh.boolean",
		Method:         "POST",
		Path:           "/blender_mesh/boolean",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("mesh", "boolean", "", "/blender_mesh/boolean"),
	},
	{
		ID:             "mesh.create",
		Method:         "POST",
		Path:           "/blender_mesh/create",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("mesh", "create", "", "/blender_mesh/create"),
	},
	{
		ID:             "mesh.decimate",
		Method:         "POST",
		Path:           "/blender_mesh/decimate",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("mesh", "decimate", "", "/blender_mesh/decimate"),
	},
	{
		ID:             "mesh.delete",
		Method:         "POST",
		Path:           "/blender_mesh/delete",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("mesh", "delete", "", "/blender_mesh/delete"),
	},
	{
		ID:             "mesh.duplicate",
		Method:         "POST",
		Path:           "/blender_mesh/duplicate",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("mesh", "duplicate", "", "/blender_mesh/duplicate"),
	},
	{
		ID:             "mesh.mesh_op",
		Method:         "POST",
		Path:           "/blender_mesh/mesh_op",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("mesh", "mesh_op", "", "/blender_mesh/mesh_op"),
	},
	{
		ID:             "mesh.modifier",
		Method:         "POST",
		Path:           "/blender_mesh/modifier",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("mesh", "modifier", "", "/blender_mesh/modifier"),
	},
	{
		ID:             "mesh.origin_cursor",
		Method:         "POST",
		Path:           "/blender_mesh/origin_cursor",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("mesh", "origin_cursor", "", "/blender_mesh/origin_cursor"),
	},
	{
		ID:             "mesh.remesh",
		Method:         "POST",
		Path:           "/blender_mesh/remesh",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("mesh", "remesh", "", "/blender_mesh/remesh"),
	},
	{
		ID:             "mesh.simplify_geometry",
		Method:         "POST",
		Path:           "/blender_mesh/simplify_geometry",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("mesh", "simplify_geometry", "", "/blender_mesh/simplify_geometry"),
	},
	{
		ID:             "mesh.transform",
		Method:         "POST",
		Path:           "/blender_mesh/transform",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("mesh", "transform", "", "/blender_mesh/transform"),
	},
	{
		ID:             "mesh.uv_unwrap",
		Method:         "POST",
		Path:           "/blender_mesh/uv_unwrap",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("mesh", "uv_unwrap", "", "/blender_mesh/uv_unwrap"),
	},
	{
		ID:             "physics_sim.add_force_field",
		Method:         "POST",
		Path:           "/blender_physics_sim/add_force_field",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("physics_sim", "add_force_field", "", "/blender_physics_sim/add_force_field"),
	},
	{
		ID:             "physics_sim.bake_fluid",
		Method:         "POST",
		Path:           "/blender_physics_sim/bake_fluid",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("physics_sim", "bake_fluid", "", "/blender_physics_sim/bake_fluid"),
	},
	{
		ID:             "physics_sim.configure_physics",
		Method:         "POST",
		Path:           "/blender_physics_sim/configure_physics",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("physics_sim", "configure_physics", "", "/blender_physics_sim/configure_physics"),
	},
	{
		ID:             "physics_sim.setup_cloth",
		Method:         "POST",
		Path:           "/blender_physics_sim/setup_cloth",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("physics_sim", "setup_cloth", "", "/blender_physics_sim/setup_cloth"),
	},
	{
		ID:             "physics_sim.setup_rigid_body",
		Method:         "POST",
		Path:           "/blender_physics_sim/setup_rigid_body",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("physics_sim", "setup_rigid_body", "", "/blender_physics_sim/setup_rigid_body"),
	},
	{
		ID:             "python_exec.execute",
		Method:         "POST",
		Path:           "/execute_blender_python",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("python_exec", "execute", "", "/execute_blender_python"),
	},
	{
		ID:             "render_pipeline.bake_textures",
		Method:         "POST",
		Path:           "/blender_render_pipeline/bake_textures",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render_pipeline", "bake_textures", "", "/blender_render_pipeline/bake_textures"),
	},
	{
		ID:             "render_pipeline.export_unity_fbx",
		Method:         "POST",
		Path:           "/blender_render_pipeline/export_unity_fbx",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render_pipeline", "export_unity_fbx", "", "/blender_render_pipeline/export_unity_fbx"),
	},
	{
		ID:             "render_pipeline.generate_lods",
		Method:         "POST",
		Path:           "/blender_render_pipeline/generate_lods",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render_pipeline", "generate_lods", "", "/blender_render_pipeline/generate_lods"),
	},
	{
		ID:             "render_pipeline.render_anim",
		Method:         "POST",
		Path:           "/blender_render_pipeline/render_anim",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render_pipeline", "render_anim", "", "/blender_render_pipeline/render_anim"),
	},
	{
		ID:             "render_pipeline.render_image",
		Method:         "POST",
		Path:           "/blender_render_pipeline/render_image",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render_pipeline", "render_image", "", "/blender_render_pipeline/render_image"),
	},
	{
		ID:             "render_pipeline.vfx_shadow_catcher",
		Method:         "POST",
		Path:           "/blender_render_pipeline/vfx_shadow_catcher",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render_pipeline", "vfx_shadow_catcher", "", "/blender_render_pipeline/vfx_shadow_catcher"),
	},
	{
		ID:             "render_pipeline.vfx_tracking",
		Method:         "POST",
		Path:           "/blender_render_pipeline/vfx_tracking",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render_pipeline", "vfx_tracking", "", "/blender_render_pipeline/vfx_tracking"),
	},
	{
		ID:             "rigging_anim.apply_hair_groom",
		Method:         "POST",
		Path:           "/blender_rigging_anim/apply_hair_groom",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("rigging_anim", "apply_hair_groom", "", "/blender_rigging_anim/apply_hair_groom"),
	},
	{
		ID:             "rigging_anim.create_armature",
		Method:         "POST",
		Path:           "/blender_rigging_anim/create_armature",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("rigging_anim", "create_armature", "", "/blender_rigging_anim/create_armature"),
	},
	{
		ID:             "rigging_anim.create_hair_curves",
		Method:         "POST",
		Path:           "/blender_rigging_anim/create_hair_curves",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("rigging_anim", "create_hair_curves", "", "/blender_rigging_anim/create_hair_curves"),
	},
	{
		ID:             "rigging_anim.pose_bone",
		Method:         "POST",
		Path:           "/blender_rigging_anim/pose_bone",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("rigging_anim", "pose_bone", "", "/blender_rigging_anim/pose_bone"),
	},
	{
		ID:             "rigging_anim.set_keyframe",
		Method:         "POST",
		Path:           "/blender_rigging_anim/set_keyframe",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("rigging_anim", "set_keyframe", "", "/blender_rigging_anim/set_keyframe"),
	},
	{
		ID:             "rigging_anim.setup_humanoid_rig",
		Method:         "POST",
		Path:           "/blender_rigging_anim/setup_humanoid_rig",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("rigging_anim", "setup_humanoid_rig", "", "/blender_rigging_anim/setup_humanoid_rig"),
	},
	{
		ID:             "rigging_anim.setup_ik",
		Method:         "POST",
		Path:           "/blender_rigging_anim/setup_ik",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("rigging_anim", "setup_ik", "", "/blender_rigging_anim/setup_ik"),
	},
	{
		ID:             "rigging_anim.timeline_range",
		Method:         "POST",
		Path:           "/blender_rigging_anim/timeline_range",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("rigging_anim", "timeline_range", "", "/blender_rigging_anim/timeline_range"),
	},
	{
		ID:             "rigging_anim.turntable",
		Method:         "POST",
		Path:           "/blender_rigging_anim/turntable",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("rigging_anim", "turntable", "", "/blender_rigging_anim/turntable"),
	},
	{
		ID:             "scene.busy",
		Method:         "POST",
		Path:           "/blender_scene/busy",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("scene", "busy", "", "/blender_scene/busy"),
	},
	{
		ID:             "scene.checkpoint_create",
		Method:         "POST",
		Path:           "/blender_scene/checkpoint_create",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("scene", "checkpoint_create", "", "/blender_scene/checkpoint_create"),
	},
	{
		ID:             "scene.checkpoint_list",
		Method:         "POST",
		Path:           "/blender_scene/checkpoint_list",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("scene", "checkpoint_list", "", "/blender_scene/checkpoint_list"),
	},
	{
		ID:             "scene.checkpoint_restore",
		Method:         "POST",
		Path:           "/blender_scene/checkpoint_restore",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("scene", "checkpoint_restore", "", "/blender_scene/checkpoint_restore"),
	},
	{
		ID:             "scene.collection",
		Method:         "POST",
		Path:           "/blender_scene/collection",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("scene", "collection", "", "/blender_scene/collection"),
	},
	{
		ID:             "scene.hierarchy",
		Method:         "POST",
		Path:           "/blender_scene/hierarchy",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("scene", "hierarchy", "", "/blender_scene/hierarchy"),
	},
	{
		ID:             "scene.info",
		Method:         "POST",
		Path:           "/blender_scene/info",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("scene", "info", "", "/blender_scene/info"),
	},
	{
		ID:             "scene.job_cancel",
		Method:         "POST",
		Path:           "/blender_scene/job_cancel",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("scene", "job_cancel", "", "/blender_scene/job_cancel"),
	},
	{
		ID:             "scene.job_list",
		Method:         "POST",
		Path:           "/blender_scene/job_list",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("scene", "job_list", "", "/blender_scene/job_list"),
	},
	{
		ID:             "scene.job_status",
		Method:         "POST",
		Path:           "/blender_scene/job_status",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("scene", "job_status", "", "/blender_scene/job_status"),
	},
	{
		ID:             "scene.performance",
		Method:         "POST",
		Path:           "/blender_scene/performance",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("scene", "performance", "", "/blender_scene/performance"),
	},
	{
		ID:             "scene.purge_orphans",
		Method:         "POST",
		Path:           "/blender_scene/purge_orphans",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("scene", "purge_orphans", "", "/blender_scene/purge_orphans"),
	},
	{
		ID:             "scene.regen",
		Method:         "POST",
		Path:           "/blender_scene/regen",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("scene", "regen", "", "/blender_scene/regen"),
	},
	{
		ID:             "search_online_assets.search",
		Method:         "POST",
		Path:           "/search_online_assets",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("search_online_assets", "search", "", "/search_online_assets"),
	},
	{
		ID:             "simplify_geometry.simplify",
		Method:         "POST",
		Path:           "/simplify_geometry",
		Summary:        "",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("simplify_geometry", "simplify", "", "/simplify_geometry"),
	},
}

// codeOrchStopwords filters two-letter and short common-word substrings
// that pollute ranking via the substring-contains rule. Without them, a
// search for "list links" matches every endpoint whose description
// contains "is enrolled" because "is" is two chars and the matcher
// accepts kw.contains(t) || t.contains(kw).
var codeOrchStopwords = map[string]bool{
	"a": true, "an": true, "and": true, "are": true, "as": true,
	"at": true, "be": true, "by": true, "for": true, "from": true,
	"has": true, "in": true, "is": true, "it": true, "its": true,
	"of": true, "on": true, "or": true, "that": true, "the": true,
	"this": true, "to": true, "was": true, "will": true, "with": true,
	"your": true, "you": true, "any": true, "all": true,
}

// codeOrchKeywords produces the lowercase token stream used for search
// ranking. Defined at package level so the registry initializer can call it
// inline above without pulling in a separate precompute step.
func codeOrchKeywords(resource, endpoint, summary, path string) []string {
	raw := strings.ToLower(resource + " " + endpoint + " " + summary + " " + path)
	raw = strings.Map(func(r rune) rune {
		switch r {
		case '_', '-', '/', '{', '}', '.', ',', ':', ';':
			return ' '
		}
		return r
	}, raw)
	out := make([]string, 0, 16)
	seen := map[string]bool{}
	for _, tok := range strings.Fields(raw) {
		if len(tok) < 3 || codeOrchStopwords[tok] || seen[tok] {
			continue
		}
		seen[tok] = true
		out = append(out, tok)
	}
	return out
}

func codeOrchEndpointMetadata(ep *codeOrchEndpoint) map[string]any {
	out := map[string]any{
		"endpoint_id": ep.ID,
		"method":      ep.Method,
		"path":        ep.Path,
		"summary":     ep.Summary,
	}
	return out
}

func findCodeOrchEndpoint(id string) *codeOrchEndpoint {
	for i := range codeOrchEndpoints {
		if codeOrchEndpoints[i].ID == id {
			return &codeOrchEndpoints[i]
		}
	}
	return nil
}

const (
	codeOrchSearchDefaultLimit = 10
	codeOrchSearchMaxLimit     = 100
)

func codeOrchSearchLimit(args map[string]any) int {
	if v, ok := args["limit"].(float64); ok && v > 0 {
		if v > float64(codeOrchSearchMaxLimit) {
			return codeOrchSearchMaxLimit
		}
		return int(v)
	}
	return codeOrchSearchDefaultLimit
}

func handleCodeOrchSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || strings.TrimSpace(query) == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}
	limit := codeOrchSearchLimit(args)

	terms := codeOrchKeywords("", "", query, "")
	type scored struct {
		ep    *codeOrchEndpoint
		score int
	}
	results := make([]scored, 0, len(codeOrchEndpoints))
	for i := range codeOrchEndpoints {
		ep := &codeOrchEndpoints[i]
		score := 0
		for _, t := range terms {
			for _, kw := range ep.keywords {
				if kw == t {
					score += 2
				} else if strings.Contains(kw, t) || strings.Contains(t, kw) {
					score++
				}
			}
		}
		if score > 0 {
			results = append(results, scored{ep: ep, score: score})
		}
	}
	sort.SliceStable(results, func(i, j int) bool { return results[i].score > results[j].score })
	if len(results) > limit {
		results = results[:limit]
	}

	out := make([]map[string]any, 0, len(results))
	for _, r := range results {
		item := codeOrchEndpointMetadata(r.ep)
		item["score"] = r.score
		out = append(out, item)
	}
	text, err := bound.JSON(map[string]any{"count": len(out), "results": out})
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding search results: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}

func handleCodeOrchGet(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call mcp-blender_search first)"), nil
	}
	ep := findCodeOrchEndpoint(id)
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call mcp-blender_search to discover valid ids", id)), nil
	}
	if ep.Method != "GET" {
		return mcplib.NewToolResultError(fmt.Sprintf("endpoint_id %q is %s, but mcp-blender_get only permits GET endpoints", id, ep.Method)), nil
	}
	text, err := bound.JSON(codeOrchEndpointMetadata(ep))
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding endpoint metadata: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}

func handleCodeOrchExecute(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call mcp-blender_search first)"), nil
	}

	ep := findCodeOrchEndpoint(id)
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call mcp-blender_search to discover valid ids", id)), nil
	}

	params, _ := args["params"].(map[string]any)
	if params == nil {
		params = map[string]any{}
	}

	c, platformSession, err := newMCPClient(ctx)
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	if platformSession != nil {
		defer platformSession.ZeroCredentials()
	}
	if err := cli.AdoptMCPOutputSemantics(platformSession, params); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path := ep.Path
	for _, p := range ep.Positional {
		if v, ok := params[p]; ok && strings.Contains(path, "{"+p+"}") {
			path = strings.ReplaceAll(path, "{"+p+"}", mcpPathValue(v))
			delete(params, p)
		}
	}

	hdrs := make(map[string]string, len(ep.HeaderOverrides)+len(ep.HeaderParams))
	for k, v := range ep.HeaderOverrides {
		hdrs[k] = v
	}
	for _, binding := range ep.HeaderParams {
		if binding.Default != "" {
			hdrs[binding.WireName] = binding.Default
		}
		for _, key := range []string{binding.PublicName, binding.WireName} {
			if v, ok := params[key]; ok {
				hdrs[binding.WireName] = formatMCPParamValue(v)
				delete(params, key)
				break
			}
		}
	}
	if len(hdrs) == 0 {
		hdrs = nil
	}

	// Route params to their runtime slots. GET/DELETE params are query
	// strings; write methods split spec-declared query params from the
	// remaining params used as the request body below.
	query := map[string]string{}
	if ep.Method == "GET" || ep.Method == "DELETE" {
		for k, v := range params {
			query[codeOrchWireQueryName(ep.QueryParams, k)] = formatMCPParamValue(v)
		}
	} else {
		// Route spec-declared in:query params to the query string for write
		// methods too. Without this, a query param (e.g. sendToLedger on
		// PUT /ledger/voucher/{id}) wrongly lands in the JSON body and the
		// API silently ignores it or rejects the request. The remaining
		// params stay in the map for codeOrchWriteBody (the JSON body).
		if enc := codeOrchSplitQuery(ep.QueryParams, params); enc != "" {
			sep := "?"
			if strings.Contains(path, "?") {
				sep = "&"
			}
			path += sep + enc
		}
	}

	writeBody := func() any {
		if ep.BodyIsArray {
			return codeOrchArrayBody(params)
		}
		return codeOrchWriteBody(params)
	}
	var data json.RawMessage
	switch ep.Method {
	case "GET":
		if len(hdrs) > 0 {
			if ep.Mutating {
				data, err = c.GetMutatingWithHeaders(ctx, path, query, hdrs)
			} else {
				data, err = c.GetWithHeaders(ctx, path, query, hdrs)
			}
		} else {
			if ep.Mutating {
				data, err = c.GetMutating(ctx, path, query)
			} else {
				data, err = c.Get(ctx, path, query)
			}
		}
	case "DELETE":
		if len(hdrs) > 0 {
			data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, query, hdrs)
		} else {
			data, _, err = c.DeleteWithParams(ctx, path, query)
		}
	case "POST":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PostWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Post(ctx, path, body)
		}
	case "PUT":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PutWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Put(ctx, path, body)
		}
	case "PATCH":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PatchWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Patch(ctx, path, body)
		}
	default:
		return mcplib.NewToolResultError(fmt.Sprintf("unsupported method %q", ep.Method)), nil
	}
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	text := bound.EndpointResponse(ep.Method, data)
	if platformSession != nil {
		text = bound.WithMetadata(text, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(text), nil
}

// codeOrchWriteBody returns the value handed to the client layer as the
// request body for write methods (POST/PUT/PATCH). It MUST be the structured
// params map, never pre-marshaled bytes.
//
// client.do() marshals the body value exactly once. Handing it []byte makes
// json.Marshal([]byte) emit a base64-encoded JSON *string*, so the API
// receives "eyJ...==" where it expects the request object. Strict JSON APIs
// reject that as the wrong type at the body root. GET/DELETE carry no body,
// so this defect stays latent until the first write attempt.
func codeOrchWriteBody(params map[string]any) any {
	return params
}

// codeOrchArrayBody returns the request body for endpoints whose schema root
// is a bare top-level JSON array (ep.BodyIsArray). Such a body cannot be
// expressed as the params object, so the agent supplies the array under the
// conventional params key "body" (these endpoints have no flattened named
// params, so there is no collision risk). When present and array-shaped it is
// sent as the top-level array the API expects. Otherwise params is returned
// unchanged so a malformed call fails loudly at the API (HTTP 422) instead of
// silently sending the wrong shape or a partial write — financial mutations
// are never retried with body-variant guesses (broken-convenience guardrail).
func codeOrchArrayBody(params map[string]any) any {
	if v, ok := params["body"]; ok {
		if arr, ok := v.([]any); ok {
			return arr
		}
	}
	return params
}

// codeOrchSplitQuery removes spec-declared in:query params from params and
// returns them URL-encoded for appending to the request path. The remaining
// entries stay in the map for codeOrchWriteBody (the JSON body), so a write
// method's query parameters never get buried in the body. Mutates params by
// design (deletes the consumed query keys).
func codeOrchSplitQuery(queryParams []codeOrchParamBinding, params map[string]any) string {
	uv := neturl.Values{}
	for _, q := range queryParams {
		for _, key := range []string{q.PublicName, q.WireName} {
			if key == "" {
				continue
			}
			if v, ok := params[key]; ok {
				uv.Set(q.WireName, formatMCPParamValue(v))
				delete(params, key)
				break
			}
		}
	}
	return uv.Encode()
}

func codeOrchWireQueryName(queryParams []codeOrchParamBinding, name string) string {
	for _, q := range queryParams {
		if q.PublicName == name || q.WireName == name {
			return q.WireName
		}
	}
	return name
}
