// Copyright 2026 pakkio and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"mcp-blender-pp-cli/internal/cli"
	"mcp-blender-pp-cli/internal/client"
	"mcp-blender-pp-cli/internal/cliutil"
	"mcp-blender-pp-cli/internal/config"
	"mcp-blender-pp-cli/internal/learn"
	"mcp-blender-pp-cli/internal/mcp/bound"
	"mcp-blender-pp-cli/internal/mcp/cobratree"
	"mcp-blender-pp-cli/internal/platform"
)

const (
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	installFreshTenantGate(s)
	// Code-orchestration mode — the full surface is covered by registry tools
	// (<api>_search, <api>_get, and <api>_execute). Endpoint-mirror tools are suppressed.
	RegisterCodeOrchestrationTools(s)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

type mcpPageConfig struct {
	CursorParam    string
	NextCursorPath string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		// Composite values (a native []any / map[string]any from an array or
		// object param) reach this path when bound to a query or path slot;
		// JSON-encode them so the wire value is valid JSON rather than Go's
		// "[a b c]" / "map[...]" rendering. Body params never come through
		// here — they are stored natively in bodyArgs and marshalled there.
		if b, err := json.Marshal(v); err == nil {
			return string(b)
		}
		return fmt.Sprintf("%v", v)
	}
}

func mcpPathValue(v any) string {
	return cliutil.EscapePathParam(formatMCPParamValue(v))
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, pageConfig mcpPageConfig, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, platformSession, err := newMCPClient(ctx)
		if err != nil {
			return mcpToolError(err.Error()), nil
		}
		if platformSession != nil {
			defer platformSession.ZeroCredentials()
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()
		if err := cli.AdoptMCPOutputSemantics(platformSession, args); err != nil {
			return mcpToolError(err.Error()), nil
		}

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		mcpCursor := ""
		if pageConfig.CursorParam != "" {
			knownArgs["cursor"] = true
			if v, ok := args["cursor"]; ok {
				s, ok := v.(string)
				if !ok {
					return mcpToolError("cursor must be an opaque string returned by a previous MCP response"), nil
				}
				mcpCursor = s
				upstreamCursor, err := bound.UpstreamCursor(s)
				if err != nil {
					return mcpToolError(err.Error()), nil
				}
				if upstreamCursor != "" {
					params[pageConfig.CursorParam] = upstreamCursor
				}
			}
		}
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			case "header":
				if headers == nil {
					headers = map[string]string{}
				}
				headers[binding.WireName] = formatMCPParamValue(v)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				if readOnly {
					data, err = c.GetWithHeaders(ctx, path, params, headers)
				} else {
					data, err = c.GetMutatingWithHeaders(ctx, path, params, headers)
				}
				break
			}
			if readOnly {
				data, err = c.Get(ctx, path, params)
			} else {
				data, err = c.GetMutating(ctx, path, params)
			}
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PutQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PutQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
			}
		case "PATCH":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PatchQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PatchQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
			}
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcpToolError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcpToolTextWithPlatform("already exists (no-op)", platformSession), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcpToolError("authentication failed: " + msg +
					"\nhint: check your API credentials." +
					"\n      Run 'mcp-blender-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcpToolError("permission denied: " + msg +
					"\nhint: this API is configured without credentials; the service may be blocking the request by rate limit, geography, bot protection, or endpoint policy." +
					"\n      Run 'mcp-blender-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcpToolTextWithPlatform("already deleted (no-op)", platformSession), nil
				}
				return mcpToolError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcpToolError("rate limited: " + msg), nil
			default:
				return mcpToolError(msg), nil
			}
		}

		if binaryResponse {
			encoded := base64.StdEncoding.EncodeToString(data)
			out, err := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      encoded,
				"byte_count":       len(data),
			})
			if err != nil {
				return mcpToolError(fmt.Sprintf("encoding binary result: %v", err)), nil
			}
			if len(out) > bound.MaxBytes {
				return mcpToolError(fmt.Sprintf("binary response is too large for MCP text output: %d response bytes encode to %d base64 bytes and %d MCP result bytes, exceeding the %d byte budget. Use the companion CLI command with --output <file> to save the payload locally.", len(data), len(encoded), len(out), bound.MaxBytes)), nil
			}
			result := string(out)
			if platformSession != nil {
				result = bound.WithMetadata(result, platformSession.OutputMetadata())
			}
			return mcplib.NewToolResultText(result), nil
		}
		if pageConfig.CursorParam != "" {
			return mcpToolPageResultTextWithPlatform(method, data, pageConfig, mcpCursor, platformSession), nil
		}
		return mcpToolResultTextWithPlatform(method, data, platformSession), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	return mcpToolResultTextWithPlatform(method, data, nil)
}

func mcpToolTextWithPlatform(result string, platformSession *platform.Session) *mcplib.CallToolResult {
	if platformSession != nil {
		result = bound.WithMetadata(result, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(result)
}

func mcpToolResultTextWithPlatform(method string, data json.RawMessage, platformSession *platform.Session) *mcplib.CallToolResult {
	result := bound.EndpointResponse(method, data)
	return mcpToolTextWithPlatform(result, platformSession)
}

// mcpToolError keeps provider-controlled typed endpoint errors within the MCP
// text-result budget just like successful endpoint results.
func mcpToolError(message string) *mcplib.CallToolResult {
	return mcplib.NewToolResultError(bound.Text(message))
}

func mcpToolPageResultText(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string) *mcplib.CallToolResult {
	return mcpToolPageResultTextWithPlatform(method, data, pageConfig, cursor, nil)
}

func mcpToolPageResultTextWithPlatform(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string, platformSession *platform.Session) *mcplib.CallToolResult {
	result := bound.EndpointPageResponse(method, data, bound.PageOptions{
		Cursor:         cursor,
		CursorParam:    pageConfig.CursorParam,
		NextCursorPath: pageConfig.NextCursorPath,
	})
	if platformSession != nil {
		result = bound.WithMetadata(result, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(result)
}

func newMCPClient(ctx context.Context) (*client.Client, *platform.Session, error) {
	cfg, err := newMCPConfig()
	if err != nil {
		return nil, nil, err
	}
	c := newMCPClientFromConfig(cfg)
	session, err := cli.BindMCPClient(ctx, c)
	if err != nil {
		return nil, nil, err
	}
	return c, session, nil
}

func newMCPConfig() (*config.Config, error) {
	cfg, err := config.Load("")
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	return cfg, nil
}

func newMCPClientFromConfig(cfg *config.Config) *client.Client {
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c
}

func mcpDBPath() (string, error) {
	dir, err := cliutil.DataDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "data.db"), nil
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	text, err := bound.JSON(v)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	paths := map[string]string{}
	if dir, err := cliutil.ConfigDir(); err == nil {
		paths["config_dir"] = dir
	}
	if dir, err := cliutil.DataDir(); err == nil {
		paths["data_dir"] = dir
	}
	if dir, err := cliutil.StateDir(); err == nil {
		paths["state_dir"] = dir
	}
	if dir, err := cliutil.CacheDir(); err == nil {
		paths["cache_dir"] = dir
	}
	ctx := map[string]any{
		"api":         "mcp-blender",
		"description": "Printing Press CLI for Mcp Blender.",
		"archetype":   "content",
		"tool_count":  75,
		"paths":       paths,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion mcp-blender-pp-cli binary.",
		// learn_protocol is generated from the single shared source of
		// truth (the exported constant internal/learn.RecallFirstProtocol)
		// also consumed by the CLI agent-context command, so the MCP and
		// CLI agent surfaces cannot drift.
		"learn_protocol": learn.RecallFirstProtocol,
		"resources": []map[string]any{
			{
				"name":        "assets",
				"description": "Online asset search (Poly Haven/Sketchfab/ambientCG) and AI text-to-3D generation (Meshy/Tripo/Trellis).",
				"endpoints":   []string{"ai_generate", "asset_browser", "import_online", "search_online"},
				"writable":    true,
			},
			{
				"name":        "camera_lighting",
				"description": "Studio/sun-sky lighting rigs, camera tracking/framing, viewport screenshots, AI visual critique.",
				"endpoints":   []string{"camera_setup", "compositor_effects", "evaluate_scene", "frame_objects", "light_setup", "look_at", "screenshot", "studio_lighting", "sun_sky_rig"},
				"writable":    true,
			},
			{
				"name":        "docs",
				"description": "Query multi-step 3D workflow recipes, parameters, and best practices on demand.",
				"endpoints":   []string{"search"},
			},
			{
				"name":        "evaluate_scene_visually",
				"description": "Standalone high-stakes entry point (also reachable via blender_camera_lighting(action=evaluate_scene)).",
				"endpoints":   []string{"evaluate"},
				"writable":    true,
			},
			{
				"name":        "import_online_asset",
				"description": "Standalone high-stakes entry point (also reachable via blender_assets(action=import_online)).",
				"endpoints":   []string{"import"},
				"writable":    true,
			},
			{
				"name":        "material",
				"description": "PBR shading, procedural grunge masks, toon shaders, alpha transparency, triplanar mapping, and material slots.",
				"endpoints":   []string{"assign", "create", "edit_nodes", "pbr_setup", "procedural_grunge", "slots", "toon_shader", "transparency", "triplanar"},
				"writable":    true,
			},
			{
				"name":        "mesh",
				"description": "3D modeling, transforms, boolean CSG, decimation, voxel remesh, UV unwrap, and modifiers.",
				"endpoints":   []string{"apply_transform", "boolean", "create", "decimate", "delete", "duplicate", "mesh_op", "modifier", "origin_cursor", "remesh", "simplify_geometry", "transform", "uv_unwrap"},
				"writable":    true,
			},
			{
				"name":        "physics_sim",
				"description": "Rigid body physics, cloth simulation, wind/vortex forces, fluid domain baking, scene physics settings.",
				"endpoints":   []string{"add_force_field", "bake_fluid", "configure_physics", "setup_cloth", "setup_rigid_body"},
				"writable":    true,
			},
			{
				"name":        "python_exec",
				"description": "Direct raw Python execution escape hatch inside Blender.",
				"endpoints":   []string{"execute"},
				"writable":    true,
			},
			{
				"name":        "render_pipeline",
				"description": "Still/animation rendering, PBR texture baking, Unity FBX export, LOD chain generation, VFX tracking.",
				"endpoints":   []string{"bake_textures", "export_unity_fbx", "generate_lods", "render_anim", "render_image", "vfx_shadow_catcher", "vfx_tracking"},
				"writable":    true,
			},
			{
				"name":        "rigging_anim",
				"description": "Armatures, bone posing, IK rigs, hair curves creation/grooming, animation keyframes, turntable animation.",
				"endpoints":   []string{"apply_hair_groom", "create_armature", "create_hair_curves", "pose_bone", "set_keyframe", "setup_humanoid_rig", "setup_ik", "timeline_range", "turntable"},
				"writable":    true,
			},
			{
				"name":        "scene",
				"description": "Scene inspection, hierarchy organization, checkpoint rollback, orphan purging, and background jobs.",
				"endpoints":   []string{"busy", "checkpoint_create", "checkpoint_list", "checkpoint_restore", "collection", "hierarchy", "info", "job_cancel", "job_list", "job_status", "performance", "purge_orphans", "regen"},
				"writable":    true,
			},
			{
				"name":        "search_online_assets",
				"description": "Standalone high-stakes entry point (also reachable via blender_assets(action=search_online)).",
				"endpoints":   []string{"search"},
			},
			{
				"name":        "simplify_geometry",
				"description": "Standalone high-stakes entry point (also reachable via blender_mesh(action=simplify_geometry)).",
				"endpoints":   []string{"simplify"},
				"writable":    true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
