"""Tripo3D: AI Text-to-3D Model Generation.
Requires TRIPO_API_KEY environment variable.
https://platform.tripo3d.ai/
"""

import os
from pathlib import Path
import httpx

from ..cache import find_cached_file
from .base import AssetHit, DownloadedAsset, ProviderError

BASE_URL = "https://api.tripo3d.ai/v2/openapi"


class TripoProvider:
    name = "tripo"
    requires_token = True

    def _get_token(self) -> str | None:
        return os.environ.get("TRIPO_API_KEY")

    def is_available(self) -> bool:
        return bool(self._get_token())

    async def search(self, query: str, asset_type: str, limit: int) -> list[AssetHit]:
        if asset_type != "MODEL":
            return []

        return [
            AssetHit(
                id=f"tripo_{query.replace(' ', '_')[:30]}",
                provider=self.name,
                name=f"Tripo3D Generation: '{query}'",
                asset_type="MODEL",
                license="User Generated",
                requires_token=True,
                tri_count_hint=25000,
                extra={"prompt": query, "note": "Requires TRIPO_API_KEY"},
            )
        ]

    async def download(self, asset_id: str, dest_dir: str) -> DownloadedAsset:
        cached = find_cached_file(self.name, asset_id)
        if cached is not None:
            return DownloadedAsset(
                filepath=str(cached),
                provider=self.name,
                asset_id=asset_id,
                license="User Generated",
                attribution=f"'{asset_id}' generated by Tripo3D AI",
                from_cache=True,
            )

        token = self._get_token()
        if not token:
            raise ProviderError("Tripo3D requires TRIPO_API_KEY environment variable.")

        headers = {"Authorization": f"Bearer {token}"}
        prompt = asset_id.replace("tripo_", "").replace("_", " ")

        async with httpx.AsyncClient(timeout=60.0) as client:
            resp = await client.post(
                f"{BASE_URL}/task",
                headers=headers,
                json={"type": "text_to_model", "prompt": prompt},
            )
            if resp.status_code != 200:
                raise ProviderError(f"Tripo3D API request failed: HTTP {resp.status_code}")

            data = resp.json()
            task_id = data.get("data", {}).get("task_id")
            if not task_id:
                raise ProviderError(f"No task_id returned by Tripo3D: {data}")

            # Check task status
            status_resp = await client.get(f"{BASE_URL}/task/{task_id}", headers=headers)
            model_url = status_resp.json().get("data", {}).get("output", {}).get("model")
            if not model_url:
                raise ProviderError(f"Tripo3D task '{task_id}' in progress. Model download url not yet ready.")

            glb_resp = await client.get(model_url)
            if glb_resp.status_code != 200:
                raise ProviderError(f"Failed to download GLB from Tripo3D: HTTP {glb_resp.status_code}")

        out_file = Path(dest_dir) / f"{asset_id}.glb"
        out_file.parent.mkdir(parents=True, exist_ok=True)
        out_file.write_bytes(glb_resp.content)

        return DownloadedAsset(
            filepath=str(out_file),
            provider=self.name,
            asset_id=asset_id,
            license="User Generated",
            attribution=f"'{asset_id}' generated by Tripo3D",
            from_cache=False,
        )
